# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-austinrp-github-io-lagrange'

  #google-ID: 'UA-112060364-1'

menu:
- {name: 'Education', path: 'menu', url: 'education'}
- {name: 'Research', path: 'menu', url: 'research'}
- {name: 'Achievements', path: 'menu', url: 'achievements'}
- {name: 'CV', path: 'assets/docs', url: 'austinrp_cv.pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/austinrp'}
- {icon: 'envelope', link: 'mailto:austin.pahl@colorado.edu'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/austinrpahl/'}
#- {icon: 'rss-square', link: '/feed.xml'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
